After:
  - 'framework/*'
  - 'cms/*'
---
Injector:
  MessageSerializer:
    class:  Ntb\QueueAdapter\JSONSerializer
  QueueAdapter:
    class:  Ntb\QueueAdapter\RedisAdapter
    constructor:
      0:
        host: '127.0.0.1'
        port: 6379
        scheme: 'tcp'
